### ISSUE TITLE
Erro HTTP

### ISSUE THREAD

**Issue by andercrist** [facfelipe/nfse-curitiba-php#1]
Boa noite, estou tentando utilizar a ferramenta porém retorna erro:

SoapFault: HTTP - Could not connect to host

Sabe o que pode ser?

**Comment by facfelipe** [comment]
Olá, 

Como trata-se de um erro genérico de falha de conexão via SOAP,  podem ser várias coisas.

Um dos principais pontos que é necessário para comunicação com os webservices  da  prefeitura é um certificado digital válido e autorizado para a emissão de NFS-e, que deve ser informado na biblioteca.

Como esta lib foi desenvolvida em 2018, pode  ser que exista uma  nova versão de WSDL, que aponte  para um novo host de  emissão,  o link para ele pode ser trocado em constante na classe principal.

Além disso,  pode ser que de lá para cá muita coisa tenha mudado, sugiro  programar uma integração em PHP puro, deixando funcional para ter certeza que todo o processo  com seu ambiente esteja ok, para aí então implementar essa lib, que o objetivo principal é geraração dos XML's via array, tirando a necessidade de ficar montando todos XML's manualmente através de concatenação de strings.

**Comment by andercrist** [comment]
Obrigado pela resposta, acabei fazendo de outra forma seguindo a documentação da prefeitura.
